# Generated by Django 4.2.2 on 2023-07-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-red', max_length=20, verbose_name='Navbar')),
                ('small_screens_navbar', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-white', max_length=20, verbose_name='Navbar on small screens')),
                ('header', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-red', max_length=20, verbose_name='Header')),
                ('first_grid_icon', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-red', max_length=20, verbose_name='First grid icon')),
                ('second_grid_icon', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-red', max_length=20, verbose_name='Second grid icon')),
                ('second_grid_background', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-light-grey', max_length=20, verbose_name='Second grid background')),
                ('second_grid_p_color', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-grey', max_length=20, verbose_name='Second grid text color')),
                ('rom_version_container', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-black', max_length=20, verbose_name='Rom version container')),
                ('back_home_button', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='w3-black', max_length=20, verbose_name='Back home button')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Theme',
            },
        ),
    ]
