# Generated by Django 4.2.2 on 2023-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Navbar')),
                ('navbar_hover', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Navbar hover color')),
                ('small_screens_navbar', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Navbar on small screens')),
                ('small_screens_menu', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Menu color on small screens')),
                ('small_screens_menu_hover', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Menu hover color on small screens')),
                ('header', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Header')),
                ('first_grid_icon', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='First grid icon')),
                ('second_grid_icon', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Second grid icon')),
                ('second_grid_background', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='light-grey', max_length=20, verbose_name='Second grid background')),
                ('second_grid_p_color', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='grey', max_length=20, verbose_name='Second grid text color')),
                ('rom_version_container', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='black', max_length=20, verbose_name='Rom version container')),
                ('back_home_button', models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='black', max_length=20, verbose_name='Back home button')),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='TipOfTheDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(verbose_name='Main text')),
                ('additional_text', models.TextField(verbose_name='Second text')),
            ],
            options={
                'verbose_name_plural': 'Tip of the day',
            },
        ),
    ]
