# Generated by Django 4.2.2 on 2023-07-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thememodel',
            options={'verbose_name_plural': 'Themes'},
        ),
    ]
