# Generated by Django 4.2.3 on 2023-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_thememodel_back_home_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememodel',
            name='back_home_button',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='black', max_length=20, verbose_name='Back home button'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='first_grid_icon',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='First grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='header',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='navbar',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Navbar'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='navbar_hover',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Navbar hover color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='rom_version_container',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='black', max_length=20, verbose_name='Rom version container'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_background',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='light-grey', max_length=20, verbose_name='Second grid background'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_icon',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Second grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_p_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='grey', max_length=20, verbose_name='Second grid text color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_menu',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='red', max_length=20, verbose_name='Menu color on small screens'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_menu_hover',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Menu hover color on small screens'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_navbar',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('sand', 'sand'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black'), ('white', 'white')], default='white', max_length=20, verbose_name='Navbar on small screens'),
        ),
    ]
