# Generated by Django 6.0 on 2025-12-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_thememodel_header_button'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeModel',
        ),
        migrations.DeleteModel(
            name='TipOfTheDayModel',
        ),
    ]
