# Generated by Django 4.2.2 on 2023-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_thememodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thememodel',
            name='theme_name',
            field=models.CharField(default='Custom Colors', max_length=30),
        ),
    ]
