# Generated by Django 4.2.2 on 2023-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_thememodel_theme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thememodel',
            name='theme_name',
        ),
        migrations.RemoveField(
            model_name='thememodel',
            name='user',
        ),
        migrations.AddField(
            model_name='thememodel',
            name='navbar_hover',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='white', max_length=20, verbose_name='Navbar hover color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='back_home_button',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='black', max_length=20, verbose_name='Back home button'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='first_grid_icon',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='red', max_length=20, verbose_name='First grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='header',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='red', max_length=20, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='navbar',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='red', max_length=20, verbose_name='Navbar'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='rom_version_container',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='black', max_length=20, verbose_name='Rom version container'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_background',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='light-grey', max_length=20, verbose_name='Second grid background'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_icon',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='red', max_length=20, verbose_name='Second grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_p_color',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='grey', max_length=20, verbose_name='Second grid text color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_navbar',
            field=models.CharField(choices=[('red', 'red'), ('pink', 'pink'), ('purple', 'purple'), ('deep-purple', 'deep-purple'), ('indigo', 'indigo'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('cyan', 'cyan'), ('teal', 'teal'), ('green', 'green'), ('light-green', 'light-green'), ('lime', 'lime'), ('khaki', 'khaki'), ('yellow', 'yellow'), ('amber', 'amber'), ('orange', 'orange'), ('deep-orange', 'deep-orange'), ('blue-grey', 'blue-grey'), ('brown', 'brown'), ('light-grey', 'light-grey'), ('grey', 'grey'), ('dark-grey', 'dark-grey'), ('black', 'black')], default='white', max_length=20, verbose_name='Navbar on small screens'),
        ),
    ]
