# Generated by Django 4.2.3 on 2023-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_thememodel_back_home_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thememodel',
            name='back_home_button',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='black', max_length=11, verbose_name='Back home button'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='first_grid_icon',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='red', max_length=11, verbose_name='First grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='header',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='red', max_length=11, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='navbar',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='red', max_length=11, verbose_name='Navbar'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='navbar_hover',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='white', max_length=11, verbose_name='Navbar hover color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='rom_version_container',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='black', max_length=11, verbose_name='Rom version container'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_background',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='light-grey', max_length=11, verbose_name='Second grid background'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_icon',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='red', max_length=11, verbose_name='Second grid icon'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='second_grid_p_color',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='grey', max_length=11, verbose_name='Second grid text color'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_menu',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='red', max_length=11, verbose_name='Menu color on small screens'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_menu_hover',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='white', max_length=11, verbose_name='Menu hover color on small screens'),
        ),
        migrations.AlterField(
            model_name='thememodel',
            name='small_screens_navbar',
            field=models.CharField(choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('deep-purple', 'DEEP_PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT_BLUE'), ('cyan', 'CYAN'), ('teal', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT_GREEN'), ('lime', 'LIME'), ('sand', 'SAND'), ('khaki', 'KHAKI'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP_ORANGE'), ('blue-grey', 'BLUE_GREY'), ('brown', 'BROWN'), ('light-grey', 'LIGHT_GREY'), ('grey', 'GREY'), ('dark-grey', 'DARK_GREY'), ('black', 'BLACK'), ('white', 'WHITE')], default='white', max_length=11, verbose_name='Navbar on small screens'),
        ),
    ]
