# Generated by Django 4.2.2 on 2023-07-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_thememodel_small_screens_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipOfTheDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(verbose_name='Main text')),
                ('additional_text', models.TextField(verbose_name='Second text')),
            ],
        ),
    ]
