# Generated by Django 4.2.2 on 2023-07-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_tipofthedaymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofthedaymodel',
            options={'verbose_name_plural': 'Tip of the day'},
        ),
    ]
