version: '3'

services:
  web:
    image: chebishev/aws_deploy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - static_volume:/home/app/web/staticfiles
    platform: linux/amd64
    command: gunicorn --bind=0.0.0.0:8000 XiaomiEuRomChecker.wsgi:application
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      #- ./certbot/www:/var/www/certbot/:ro
      #- ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certs:/etc/nginx/certs
    links:
      - web
    depends_on:
      - certbot
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certs:/etc/letsencrypt
      - ./letsencrypt_data:/var/lib/letsencrypt
    command:
      - certonly
      - --nginx
      - --email=atanas.chebishev@gmail.com
      - --agree-tos
      - --domain=rom-checker.site
      - --preferred-challenges=http