version: '3.8'

services:
  web:
    image: xiaomi_eu_rom_checker
    build: .
    command: gunicorn --bind 0.0.0.0:8000 XiaomiEuRomChecker.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: xiaomi.eu_rom_checker_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql:/var/lib/postgresql/data