version: '3'

services:
  web:
    image: chebishev/aws_deploy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - /tmp/app-resources/static:/app/static
    platform: linux/amd64
    command: gunicorn --bind=0.0.0.0:8000 XiaomiEuRomChecker.wsgi:application
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/apt-resources/static":/home/app/web/static
      - ./nginx/conf.d:/etc/nginx/nginx.conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro