version: '3'

services:
  web:
    # for using image from dockerhub
    image:  # it can be changed to your_hub/your_image:tag
    # for building the configuration from dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - /tmp/app-resources/static:/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/app-resources/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt/live/rom-checker.site/fullchain.pem:/etc/nginx/cert/fullchain.pem:ro
      - /etc/letsencrypt/live/rom-checker.site/privkey.pem:/etc/nginx/cert/privkey.pem:ro
    links:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx