# Generated by Django 4.2.4 on 2023-08-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=40, verbose_name='Link name')),
                ('link_url', models.URLField(verbose_name='Link URL')),
                ('short_link', models.URLField(blank=True, max_length=100, null=True, verbose_name='Short link URL')),
                ('link_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(editable=False, max_length=45, unique=True, verbose_name='Slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
    ]
