# Generated by Django 6.0 on 2025-12-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksmodel',
            name='short_link',
        ),
    ]
