# Generated by Django 4.2.2 on 2023-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='link_description',
            field=models.TextField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='link_name',
            field=models.CharField(max_length=40, verbose_name='Link name'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='link_url',
            field=models.URLField(max_length=100, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='short_link',
            field=models.URLField(blank=True, editable=False, max_length=100, null=True, verbose_name='Short link URL'),
        ),
        migrations.AlterField(
            model_name='linksmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
