# Generated by Django 4.2.2 on 2023-07-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_linksmodel_options_alter_linksmodel_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='link_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
