# Generated by Django 4.2.3 on 2023-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_linksmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='slug',
            field=models.SlugField(default='1-my link', editable=False, max_length=45, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
