# Generated by Django 4.2.3 on 2023-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_linksmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='link_url',
            field=models.URLField(verbose_name='Link URL'),
        ),
    ]
