# Generated by Django 4.2.4 on 2023-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDevicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=20)),
                ('market_name', models.CharField(max_length=40, unique=True)),
                ('rom_name', models.CharField(max_length=30)),
                ('rom_options', models.CharField(choices=[('stable', 'stable'), ('weekly', 'weekly'), ('both', 'both')], max_length=6)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Available Devices',
            },
        ),
        migrations.CreateModel(
            name='FoldersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=20, unique=True)),
                ('last_modification_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Weekly Folders',
            },
        ),
    ]
