# Generated by Django 4.2.2 on 2023-06-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabledevicesmodel',
            options={'verbose_name_plural': 'Available Devices'},
        ),
    ]
