# Generated by Django 4.2.2 on 2023-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_availabledevicesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledevicesmodel',
            name='market_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
