# Generated by Django 4.2.2 on 2023-06-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_availabledevicesmodel_market_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=20)),
                ('last_modification_date', models.DateField()),
            ],
        ),
    ]
