# Generated by Django 4.2.2 on 2023-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_folders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folders',
            new_name='FoldersModel',
        ),
    ]
