# Generated by Django 4.2.2 on 2023-07-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_foldersmodel_folder_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foldersmodel',
            options={'verbose_name_plural': 'Weekly Folders'},
        ),
    ]
