# Generated by Django 6.0 on 2025-12-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_delete_threadtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='preferred_device',
        ),
    ]
