name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REPO_VERSION: ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:${{ github.run_number }}
  REPO_LATEST: ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $REPO_VERSION
  
  push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push current version to Docker Hub
      run: docker push $REPO_VERSION
    - name: Rename to latest
      run: docker tag $REPO_VERSION $REPO_LATEST
    - name: Push latest version to Docker Hub
      run: docker push $REPO_LATEST
