name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:${{ github.run_number }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:latest
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push current version to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:${{ github.run_number }}
    - name: Push latest version to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/xiaomi.eu_rom_checker:latest
